### ISSUE TITLE
Ensure support for tilezen

### ISSUE THREAD

**Issue by tarakc02** [tarakc02/rmapzen#15]
See [this comment](https://github.com/tarakc02/rmapzen/pull/14#issuecomment-364504191).

**Comment by dpprdan** [comment]
The problem lies here 

```r
vector_path <- function(layers, x, y, z, format) {
    res <- paste("mapzen", "vector", "v1", layers, z, x, y, sep = "/")
    paste(res, format, sep = ".")
}
```

"mapzen" ought to be "tilezen".

**Comment by tarakc02** [comment]
thanks! I was just looking at this. Seems simple enough. I'm going to play with a couple of ways for the user to specify the various provider-specific options -- I like the ggmap way that you linked to earlier where related options are grouped together and there are custom functions for setting up known providers.

**Comment by dpprdan** [comment]
Agreed. There also need to be different environment variables for the respective api keys, I guess (if you want to keep all functionality in one package).

**Comment by tarakc02** [comment]
The "providers" branch (https://github.com/tarakc02/rmapzen/tree/providers) includes updates to allow the user to get/set configurable provider options. I've tested with geocode.earth and nycgeosearch for the search/geocode services, and nextzen for the vector tiles. any provider can be set up with the `mz_set_host` function, but there are already functions for those three known services (`mz_set_search_host_geocode.earth`, etc).

**Comment by tarakc02** [comment]
see `?mz_set_tile_host_nextzen`
