### ISSUE TITLE
Add Origin to request header for mz_vector_tiles()

### ISSUE THREAD

**Issue by dmi3kno** [tarakc02/rmapzen#17]
Nextzen anticipates that user would specify an origin URL:

>Specify one URL per line. If set, this API key will only allow tile requests that have an Origin header set to one of these URLs.

Can we allow users to [optionally] specify an `Origin` that we would further pass to vector_GET as part of modified request header?

![Capture](https://user-images.githubusercontent.com/13419011/55078326-340d8e00-509a-11e9-93a0-a39d50b3bb70.PNG)

**Comment by tarakc02** [comment]
Yes, thanks for catching this. I'll add the option in the next day or two.

**Comment by tarakc02** [comment]
@dmi3kno -- does the version currently on the `devel` branch work as you'd expect?
