### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by ccamara** [tarakc02/rmapzen#20]
I have just discovered this package and looks promising! Unfortunately, it is not clear to me if it is working or not and, above all,  what's its current development status. On the one hand, I can see an outdated note about mapzen shutting their services (while that was true, in January 2019 they opened again thanks to Linux Foundation), but on the other hand, I can see that the project was updated in August 2019.

**Comment by tarakc02** [comment]
Hi @ccamara! Thank you for creating this issue! I had not realized that Mapzen had opened again, and had focused development/testing on making sure the package works with other known providers (nextzen and geocode.earth primarily). I'll begin testing and developing using the re-opened Mapzen to ensure the package supports the current API. Unfortunately, I won't have much time to work on it this week, but please post any issues you happen to notice and/or if you're comfortable doing so submit pull requests. I'll update this issue once I have some time to spend on it, probably during the later part of this week or early next week.

**Comment by tarakc02** [comment]
Hi @ccamara, this package provides an API client for services that use the Mapzen software. It is already set up to use the publicly available services listed on the Mapzen website (geocode.earth and Nextzen tiles). Have you had problems in trying to use it?

**Comment by ccamara** [comment]
Hi, @tarakc02 , thanks for your answer. I will try it and let you know.
