### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [tarakc02/rmapzen#23]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`rmapzen` imports 'rgdal', 'maptools', 'rgeos' using maptools::unionSpatialPolygons rgdal::ogrListLayers rgdal::readOGR as found by `pkgapi`, only 'rgeos' is bulk imported in NAMESPACE. `maptools::unionSpatialPolygons` may be replaced by `sf::st_union`, `rgdal::ogrListLayers` by `sf::st_layers`, and `rgdal::readOGR` by `sf::st_read`, all in R/as-sp.R. Please fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
@tarakc02 See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN.

**Comment by tarakc02** [comment]
i've made the changes and run checks on mac, windows, and linux. However, when I tried to submit, I see the CRAN package team is on vacation until August 7, so I will have to try submitting again then. Since the change isn't on CRAN yet, I'm re-opening this issue until it is. Noting while I'm at it that `geojsonio` still relies on some of the retiring packages, but I need to keep it as a dependency, hoping they are also going to update their package.

**Comment by rsbivand** [comment]
@tarakc02 Thanks. I don't think that https://cran.r-project.org/package=geojsonio even weakly depends on retiring packages, I attach my most recent check log from current `sp` (evolution status 2 using `sf` not `rgdal`), and without retiring packages on the library path: 
[00check.log](https://github.com/tarakc02/rmapzen/files/12148657/00check.log)
`sp` itself still suggests retiring packages, but does not use them under evolution status 2 or when they are not available. When CMD check is run on the same platform on released `rmapzen`, this log is the outcome: 
[00check.log](https://github.com/tarakc02/rmapzen/files/12148697/00check.log). However, your current repository master gives success: 
[00check.log](https://github.com/tarakc02/rmapzen/files/12148729/00check.log). So you should be OK to submit when CRAN is back from the maintenance break. Thanks for your understanding!

**Comment by tarakc02** [comment]
^ ah thanks for the clarification, I was mis-reading the warning when I loaded the package -- `geojsonio` loads `sp`, and loading `sp` causes the legacy packages message. Glad to hear that won't cause any issues though.

**Comment by tarakc02** [comment]
rmapzen 0.5.0 is on cran now, no longer imports retiring sp packages

**Comment by rsbivand** [comment]
Thanks for your cooperation!
